# Generated by Django 5.0.4 on 2024-05-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('packing', 'Packing'), ('shipping', 'Shipping'), ('delivered', 'Delivered')], default='processing', max_length=20),
        ),
    ]
