# Generated by Django 5.0.4 on 2024-05-06 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_adress'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adress',
            new_name='Address',
        ),
    ]
